/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DefectsRouteImport } from './routes/defects'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as MediaRouteImport } from './routes/media'
import { Route as RoadsIndexRouteImport } from './routes/roads/index'
import { Route as RoadsIdRouteImport } from './routes/roads/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DefectsRoute = DefectsRouteImport.update({
  id: '/defects',
  path: '/defects',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsIndexRoute = RoadsIndexRouteImport.update({
  id: '/roads/',
  path: '/roads/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsIdRoute = RoadsIdRouteImport.update({
  id: '/roads/$id',
  path: '/roads/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/defects': typeof DefectsRoute
  '/gallery': typeof GalleryRoute
  '/maintenance': typeof MaintenanceRoute
  '/media': typeof MediaRoute
  '/roads/$id': typeof RoadsIdRoute
  '/roads/': typeof RoadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/defects': typeof DefectsRoute
  '/gallery': typeof GalleryRoute
  '/maintenance': typeof MaintenanceRoute
  '/media': typeof MediaRoute
  '/roads/$id': typeof RoadsIdRoute
  '/roads': typeof RoadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/defects': typeof DefectsRoute
  '/gallery': typeof GalleryRoute
  '/maintenance': typeof MaintenanceRoute
  '/media': typeof MediaRoute
  '/roads/$id': typeof RoadsIdRoute
  '/roads/': typeof RoadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/defects'
    | '/gallery'
    | '/maintenance'
    | '/media'
    | '/roads/$id'
    | '/roads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/defects'
    | '/gallery'
    | '/maintenance'
    | '/media'
    | '/roads/$id'
    | '/roads'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/defects'
    | '/gallery'
    | '/maintenance'
    | '/media'
    | '/roads/$id'
    | '/roads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DefectsRoute: typeof DefectsRoute
  GalleryRoute: typeof GalleryRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MediaRoute: typeof MediaRoute
  RoadsIdRoute: typeof RoadsIdRoute
  RoadsIndexRoute: typeof RoadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defects': {
      id: '/defects'
      path: '/defects'
      fullPath: '/defects'
      preLoaderRoute: typeof DefectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roads/': {
      id: '/roads/'
      path: '/roads'
      fullPath: '/roads/'
      preLoaderRoute: typeof RoadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roads/$id': {
      id: '/roads/$id'
      path: '/roads/$id'
      fullPath: '/roads/$id'
      preLoaderRoute: typeof RoadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DefectsRoute: DefectsRoute,
  GalleryRoute: GalleryRoute,
  MaintenanceRoute: MaintenanceRoute,
  MediaRoute: MediaRoute,
  RoadsIdRoute: RoadsIdRoute,
  RoadsIndexRoute: RoadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
