import type { MaintenanceTask } from "@/types";

export const maintenanceTasks: MaintenanceTask[] = [
  { id: "MT-2026-0141", roadId: "R-PMC-003", type: "Resurfacing", status: "in_progress", priority: "critical", scheduledDate: "2026-09-10", completedDate: null, contractor: "Sadbhav Infra Pvt Ltd", estimatedCostLakh: 186, chainageFrom: 0, chainageTo: 3.1, notes: "Full-width bituminous overlay, night works only." },
  { id: "MT-2026-0142", roadId: "R-PMC-001", type: "Pothole patching", status: "scheduled", priority: "high", scheduledDate: "2026-09-28", completedDate: null, contractor: "PMC Road Dept – Zone 1", estimatedCostLakh: 12.5, chainageFrom: 0.4, chainageTo: 2.1, notes: "Cold-mix patching for 12 identified potholes." },
  { id: "MT-2026-0143", roadId: "R-BMC-001", type: "Pothole patching", status: "in_progress", priority: "high", scheduledDate: "2026-09-08", completedDate: null, contractor: "MMRDA Maintenance Cell", estimatedCostLakh: 22, chainageFrom: 1.2, chainageTo: 5.8, notes: "Mastic asphalt patching; lane closures 23:00–05:00." },
  { id: "MT-2026-0144", roadId: "R-BMC-002", type: "Resurfacing", status: "scheduled", priority: "critical", scheduledDate: "2026-10-15", completedDate: null, contractor: "TBD (tender open)", estimatedCostLakh: 240, chainageFrom: 0, chainageTo: 3.7, notes: "Post-monsoon reconstruction; tender closes 30 Sep." },
  { id: "MT-2026-0145", roadId: "R-BBMP-003", type: "Resurfacing", status: "pending", priority: "critical", scheduledDate: "2026-11-01", completedDate: null, contractor: "Unassigned", estimatedCostLakh: 210, chainageFrom: 0, chainageTo: 3.9, notes: "Awaiting budget approval from BBMP council." },
  { id: "MT-2026-0146", roadId: "R-BBMP-001", type: "Crack sealing", status: "scheduled", priority: "high", scheduledDate: "2026-09-30", completedDate: null, contractor: "KRDCL", estimatedCostLakh: 18, chainageFrom: 0, chainageTo: 5.5, notes: "Rubberised sealant on alligator cracks." },
  { id: "MT-2026-0147", roadId: "R-GCC-003", type: "Pothole patching", status: "in_progress", priority: "high", scheduledDate: "2026-09-05", completedDate: null, contractor: "GCC Bus Route Roads Dept", estimatedCostLakh: 9.8, chainageFrom: 0.5, chainageTo: 3.2, notes: "" },
  { id: "MT-2026-0148", roadId: "R-GCC-001", type: "Lane re-marking", status: "scheduled", priority: "medium", scheduledDate: "2026-09-25", completedDate: null, contractor: "Auto-Mark Traffic Systems", estimatedCostLakh: 6.4, chainageFrom: 0, chainageTo: 4.6, notes: "Thermoplastic paint, Type II glass beads." },
  { id: "MT-2026-0149", roadId: "R-NDMC-002", type: "Pothole patching", status: "scheduled", priority: "high", scheduledDate: "2026-09-22", completedDate: null, contractor: "NDMC Civil Engineering", estimatedCostLakh: 14, chainageFrom: 2.0, chainageTo: 4.9, notes: "" },
  { id: "MT-2026-0150", roadId: "R-AMC-003", type: "Resurfacing", status: "pending", priority: "critical", scheduledDate: "2026-10-30", completedDate: null, contractor: "Unassigned", estimatedCostLakh: 95, chainageFrom: 0, chainageTo: 1.7, notes: "Utility trench reinstatement pending from GUVNL." },
  { id: "MT-2026-0151", roadId: "R-PCMC-002", type: "Pothole patching", status: "pending", priority: "high", scheduledDate: "2026-10-05", completedDate: null, contractor: "Unassigned", estimatedCostLakh: 11, chainageFrom: 0, chainageTo: 3.4, notes: "" },
  { id: "MT-2026-0152", roadId: "R-PCMC-001", type: "Crack sealing", status: "scheduled", priority: "medium", scheduledDate: "2026-10-06", completedDate: null, contractor: "PCMC Road Cell", estimatedCostLakh: 15, chainageFrom: 0, chainageTo: 4.8, notes: "" },
  { id: "MT-2026-0153", roadId: "R-MCC-002", type: "Crack sealing", status: "pending", priority: "medium", scheduledDate: "2026-10-12", completedDate: null, contractor: "Unassigned", estimatedCostLakh: 8, chainageFrom: 0, chainageTo: 3.6, notes: "" },
  { id: "MT-2026-0154", roadId: "R-BBMP-004", type: "Micro-surfacing", status: "scheduled", priority: "low", scheduledDate: "2026-11-02", completedDate: null, contractor: "KRDCL", estimatedCostLakh: 32, chainageFrom: 0, chainageTo: 4.4, notes: "Preventive treatment." },
  { id: "MT-2026-0131", roadId: "R-PMC-002", type: "Crack sealing", status: "completed", priority: "medium", scheduledDate: "2026-06-15", completedDate: "2026-06-20", contractor: "PMC Road Dept – Zone 1", estimatedCostLakh: 7.2, chainageFrom: 0, chainageTo: 1.9, notes: "RHI improved 58 → 71 post-works." },
  { id: "MT-2026-0126", roadId: "R-BMC-003", type: "Micro-surfacing", status: "completed", priority: "low", scheduledDate: "2026-05-10", completedDate: "2026-05-15", contractor: "MMRDA Maintenance Cell", estimatedCostLakh: 28, chainageFrom: 0, chainageTo: 4.2, notes: "" },
  { id: "MT-2026-0118", roadId: "R-BBMP-002", type: "Lane re-marking", status: "completed", priority: "low", scheduledDate: "2026-04-15", completedDate: "2026-04-18", contractor: "Auto-Mark Traffic Systems", estimatedCostLakh: 3.1, chainageFrom: 0, chainageTo: 1.8, notes: "" },
  { id: "MT-2026-0122", roadId: "R-GCC-002", type: "Crack sealing", status: "completed", priority: "medium", scheduledDate: "2026-05-28", completedDate: "2026-06-02", contractor: "GCC Bus Route Roads Dept", estimatedCostLakh: 12, chainageFrom: 1.0, chainageTo: 5.8, notes: "" },
  { id: "MT-2026-0104", roadId: "R-NDMC-001", type: "Micro-surfacing", status: "completed", priority: "low", scheduledDate: "2026-01-05", completedDate: "2026-01-10", contractor: "NDMC Civil Engineering", estimatedCostLakh: 16, chainageFrom: 0, chainageTo: 2.3, notes: "" },
  { id: "MT-2026-0119", roadId: "R-AMC-001", type: "Crack sealing", status: "completed", priority: "medium", scheduledDate: "2026-05-01", completedDate: "2026-05-05", contractor: "AMC Engineering Dept", estimatedCostLakh: 9, chainageFrom: 0, chainageTo: 3.3, notes: "" },
];
